### ISSUE TITLE
"TypeError: Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by kibertoad** [cb1kenobi/gulp-babel-istanbul#11]
I have defined the task as suggested by the example:

```
gulp.task('coverage', function (cb) {
  gulp.src('src/**/*.js')
    .pipe(istanbul())
    .pipe(istanbul.hookRequire()) // or you could use .pipe(injectModules())
    .on('finish', function () {
      gulp.src('test/**/*.js')
        .pipe(babel())
        .pipe(injectModules())
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }))
        .on('end', cb);
    });
});
```

It crashes with

[21:05:32] TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (C:\sources\message-service\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:485:7)
    at DestroyableTransform.<anonymous> (C:\sources\message-service\Gulpfile.js:131:10)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at finishMaybe (C:\sources\message-service\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:475:14)
    at endWritable (C:\sources\message-service\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (C:\sources\message-service\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:455:41)
    at DestroyableTransform.onend (C:\sources\message-service\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:91:20)

on line
.pipe(babel())

so I presume that
`gulp.src('test/**/*.js')`
for some reason returns nothing

What could possibly be the case? There definitely are js files in the "test" folder that is located in the root folder.
I realize that it's most definitely not a gulp-babel-istanbul issue, but maybe I could update examples with useful info if I understood what blew up here :)

**Comment by cb1kenobi** [comment]
I'm not certain why this is occurring. I'll take a peek when I get a sec, but in the meantime, I quickly updated all the npm deps and published v1.5.0. Perhaps the issue was in a dependency that is now fixed?

**Comment by kibertoad** [comment]
I'll give it a try tomorrow, thank you!

**Comment by kibertoad** [comment]
Thank you, the issue is gone now. Behaviour doesn't seem to be exactly correct, yet, though - is the istanbul supposed to generate its results before tests even began executing? (code is still same as pasted above). As expected, this results in coverage being less than expected.

**Comment by cb1kenobi** [comment]
`gulp-mocha` doesn't support the instrumented source being passed in, it only accepts a list of files to run mocha against. This means the instrumented source either has to be written to disk using `gulp.dest()` before calling `pipe(mocha)`, or use [gulp-inject-modules](https://www.npmjs.com/package/gulp-inject-modules) which patches the instrumented files into Node's module system.

I use `gulp-babel-istanbul` in production and haven't had any issues. Feel free to take a peek at my `gulpfile.js`: https://github.com/appcelerator/jdklib/blob/master/gulpfile.js.
